font_family     Fira Code
font_size       11.0
copy_on_select  yes

map ctrl+v         paste_from_clipboard
map ctrl+backspace send_text all \x17

window_padding_width 4
background_opacity 0.9
include ./current-theme.conf
