# --------------- GENERAL ---------------
general {
	disable_loading_bar = false
	grace = 5
	hide_cursor = true
	no_fade_in = false
}

# --------------- BACKGROUND ---------------
background {
	monitor =
	color = rgba(333333ff)  # Solid color (RGBA hex)
}

# --------------- INPUT FIELD ---------------
input-field {
	monitor =
	size = 300, 50
	outline_thickness = 2
	dots_size = 0.3
	dots_spacing = 0.2
	dots_center = true

	outer_color = rgba(ffffff88)
	inner_color = rgba(000000aa)
	font_color = rgba(ffffffff)

	fade_on_empty = false
	placeholder_text = <i>Enter Password...</i>

	position = 0, -100
	halign = center
	valign = center
}

# --------------- CLOCK LABEL ---------------
label {
	monitor =
	text = cmd[update:1000] echo "$(date +"%I:%M %p")"
	font_size = 64
	font_family = Fira Sans
	color = rgba(333333ff)

	position = 0, 100
	halign = center
	valign = center
}

# --------------- USER LABEL ---------------
label {
	monitor =
	text = $USER
	font_size = 22
	font_family = Fira Sans
	color = rgba(ffffffcc)

	position = 0, 40
	halign = center
	valign = center
}