rem requires https://kolbi.cz/blog/2017/10/25/setuserfta-userchoice-hash-defeated-set-file-type-associations-per-user/
SetUserFTA .cpp Applications\ste.exe
SetUserFTA .cc Applications\ste.exe
SetUserFTA .c Applications\ste.exe
SetUserFTA .h Applications\ste.exe
SetUserFTA .hpp Applications\ste.exe
SetUserFTA .cs Applications\ste.exe
SetUserFTA .py Applications\ste.exe
SetUserFTA .obj Applications\ste.exe
SetUserFTA .json Applications\ste.exe
SetUserFTA .xml Applications\ste.exe
SetUserFTA .txt Applications\ste.exe
SetUserFTA .lua Applications\ste.exe
SetUserFTA .sql Applications\ste.exe
SetUserFTA .meta Applications\ste.exe
SetUserFTA .gltf Applications\ste.exe
SetUserFTA .php Applications\ste.exe
SetUserFTA .ini Applications\ste.exe
SetUserFTA .js Applications\ste.exe
SetUserFTA .html Applications\ste.exe
SetUserFTA .htm Applications\ste.exe
SetUserFTA .css Applications\ste.exe
SetUserFTA .scss Applications\ste.exe
SetUserFTA .svg Applications\ste.exe
SetUserFTA .yaml Applications\ste.exe
SetUserFTA .yml Applications\ste.exe
SetUserFTA .toml Applications\ste.exe
SetUserFTA .md Applications\ste.exe
SetUserFTA .nfo Applications\ste.exe
SetUserFTA .dat Applications\ste.exe
SetUserFTA .mtl Applications\ste.exe
SetUserFTA .glsl Applications\ste.exe
SetUserFTA .hlsl Applications\ste.exe
SetUserFTA .shader Applications\ste.exe
SetUserFTA .gitignore Applications\ste.exe
pause
