SetUserFTA .cpp Applications\sublime_text.exe
SetUserFTA .cc Applications\sublime_text.exe
SetUserFTA .c Applications\sublime_text.exe
SetUserFTA .h Applications\sublime_text.exe
SetUserFTA .hpp Applications\sublime_text.exe
SetUserFTA .cs Applications\sublime_text.exe
SetUserFTA .py Applications\sublime_text.exe
SetUserFTA .obj Applications\sublime_text.exe
SetUserFTA .json Applications\sublime_text.exe
SetUserFTA .xml Applications\sublime_text.exe
SetUserFTA .txt Applications\sublime_text.exe
SetUserFTA .lua Applications\sublime_text.exe
SetUserFTA .sql Applications\sublime_text.exe
SetUserFTA .meta Applications\sublime_text.exe
SetUserFTA .gltf Applications\sublime_text.exe
SetUserFTA .php Applications\sublime_text.exe
SetUserFTA .ini Applications\sublime_text.exe
SetUserFTA .js Applications\sublime_text.exe
SetUserFTA .html Applications\sublime_text.exe
SetUserFTA .htm Applications\sublime_text.exe
SetUserFTA .css Applications\sublime_text.exe
SetUserFTA .scss Applications\sublime_text.exe
SetUserFTA .svg Applications\sublime_text.exe
SetUserFTA .yaml Applications\sublime_text.exe
SetUserFTA .yml Applications\sublime_text.exe
SetUserFTA .toml Applications\sublime_text.exe
SetUserFTA .md Applications\sublime_text.exe
SetUserFTA .nfo Applications\sublime_text.exe
pause
